# This is a config for E2B sandbox template.
# You can use template ID (opnny87nolugjb60vzvd) or template name (jeev-vibe-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("jeev-vibe-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("jeev-vibe-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('jeev-vibe-nextjs-test')

team_id = "6aa72c03-2057-4588-b2bd-0b7728135c25"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "jeev-vibe-nextjs-test"
template_id = "opnny87nolugjb60vzvd"
